# The name of this bundle. This will be the file name of the data bundle.
# Another suggested usage is to comment out this line, so the name will be
# obtained from the file name of this config, that is, the name will be the same
# as the config file name without the extension.
name: default

# The structure of the data bundle. All the involved data will be generated and
# put into the global data file first (if data not exist), and then be bundled
# according to this structure, and then write to the data bundle file.
# Only 'features' in the structure dictionary is required and be treated
# differently. The value for the key 'features' can only be list of strings, and
# the features specified in this list will be concatenated to one dataset.
structure:
  label:
    label
  test_filters:
  - is_in_test_set
  features:
  - weight
  - height
  - BMI
  - weight_divided_by_height

# The additional arguments that will be given when initiating the data generator
# object. If the same key appears in both global config and bundle config, the
# value in the bundle config will be used.
generator_kwargs: {}
