generator_class: lifetime_feature_generator.LifetimeFeatureGenerator
concat_feature_dir: concat_features
global_feature_hdf_path: global_feature.h5

# The additional arguments that will be given when initiating the feature
# generator object.
generator_kwargs:
  data_csv_path:
    lifetime.csv
