generator_class: lifetime_feature_generator.LifetimeFeatureGenerator
data_bundles_dir: data_bundles

# The additional arguments that will be given when initiating the data generator
# object.
generator_kwargs:
  global_data_hdf_path:
    global_data.h5
  data_csv_path:
    lifetime.csv
